website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')
    # wallet_balance = db.Column(db.Float, default=0.0)  # Adding wallet_balance attribute



   








    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from flask_migrate import Migrate

db = SQLAlchemy()
DB_NAME = "database.db"



def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Key1'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    migrate = Migrate(app, db)



    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   
from flask_login import login_user, login_required, logout_user, current_user
from . import auth 


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('You have now been logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.map'))
            else:
                flash('This password is incorrect, please try again.', category='error')
        else:
            flash('This email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('The email address is already in use.', category='error')
        elif len(email) < 5:
            flash('The email should consist of more than 4 characters.', category='error')
        elif len(first_name) < 3:
            flash('The first name must be greater than 2 character.', category='error')
        elif password1 != password2:
            flash('The passwords provided do not match.', category='error')
        elif len(password1) < 6:
            flash('Your password should be minimum of 5 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Your account has now been created!', category='success')
            return redirect(url_for('views.map'))

    return render_template("sign_up.html", user=current_user)

@auth.route('/map')
@login_required
def map():
    user = User.query.filter_by(id=current_user.id).first()
    return render_template('map.html', user=user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, session 
from flask_login import login_required, current_user
from .models import Note, User 
from . import db

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def map():
    if request.method == 'POST': 
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  
            db.session.add(new_note) 
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("map.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data) 
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

@views.route('/info')
@login_required
def info():
    return render_template('info.html', user=current_user)

@views.route('/barcode.html')
def barcode():
    return render_template('barcode.html', user=current_user)

@views.route('/journey.html')
def journey():
    return render_template('journey.html', user=current_user)

@views.route('/begin_journey.html')
def begin_journey():
    return render_template('begin_journey.html', user=current_user)

@views.route('/resume_journey.html')
def resume_journey():
    return render_template('resume_journey.html', user=current_user)

@views.route('/end_journey')
def end_journey():
    return render_template('end_journey.html', user=current_user)

@views.route('/wallet', methods=['GET', 'POST']) 
@login_required 
def wallet():
    selected_amount = None  
    if request.method == 'POST':
        selected_amount = float(request.form.get('amount')) 
# Update wallet balance for the current user 
        current_user.wallet_balance += selected_amount 
        # Add transaction to the WalletTransaction model 
       # transaction = WalletTransaction(user_id=current_user.id, amount=selected_amount) 
       #db.session.add(transaction) 
    # db.session.commit() 
        flash('Your wallet has been updated!', category='success') 
        return redirect(url_for('views.wallet'))  
    return render_template('wallet.html', user=current_user, selected_amount=selected_amount)

    return render_template('wallet.html', user=current_user)

@views.route('/history.html')
def history():
    return render_template('history.html', user=current_user)

@views.route('/pricing.html')
def pricing():
    return render_template('pricing.html', user=current_user)

@views.route('/day_pass.html', methods=['GET', 'POST'])
def day_pass():
    if request.method == 'POST':
        flash("Your day pass is now active, let's get moving!", category='success')
        return redirect(url_for('views.day_pass'))
    return render_template('day_pass.html', user=current_user)

@views.route('/three_day_pass.html', methods=['GET', 'POST'])
def three_day_pass():
    if request.method == 'POST':
        flash("Your three day pass is now active, let's get moving!", category='success')
        return redirect(url_for('views.three_day_pass'))
    return render_template('three_day_pass.html', user=current_user)

@views.route('/monthly_pass.html', methods=['GET', 'POST'])
def monthly_pass():
    if request.method == 'POST':
        flash("Your monthly day pass is now active, let's get moving!", category='success')
        return redirect(url_for('views.monthly_pass'))
    return render_template('monthly_pass.html', user=current_user)

@views.route('/co2.html')
def co2():
    return render_template('co2.html', user=current_user)

website/templates/barcode.html
{% extends "base.html" %}
{% block title %}Barcode{% endblock %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<div class="container">
    <div class="icon-container">
        <a href="journey.html" style="text-decoration: none; color: inherit;">
            <i class="fas fa-qrcode"></i>
        </a>
    </div>
    <div class="speech-bubble">
        <p style="font-size: 12px;">Scan the QR code located on the bike to unlock</p> 
        <div class="speech-bubble-tail"></div>
    </div>
    <div class="textbox-container">
        <div style="position: relative;">
            <input type="text" class="camera-input">
            <a href="journey.html" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-decoration: none; color: inherit;">
                <i class="fas fa-camera camera-icon" style="font-size: 48px; color: black;"></i>
            </a>
        </div>
    </div>
    <div class="actions-container">
        <div class="flashlight-container">
            <i class="fas fa-lightbulb"></i>
        </div>
        <div class="keyboard-container">
            <i class="fas fa-keyboard"></i>
        </div>
    </div>
</div>

<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column; 
        margin-top: 20px;
        position: relative;
    }
    .icon-container {
        width: 80px; 
        height: 80px; 
        border-radius: 50%; 
        background-color: #ffffff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        border: 2px solid #ecb054;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .icon-container i {
        color: #000000;
        font-size: 48px; 
    }
    .speech-bubble {
        position: relative; 
        background-color: #ee694e;
        border: 2px solid #ee694e;
        border-radius: 20px;
        padding: 10px;
        width: 200px;
        text-align: center;
        color: #ffffff;
        margin-top: 20px; 
    }
    .speech-bubble p {
        margin: 0;
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        font-size: 12px; 
    }
    .speech-bubble-tail {
        position: absolute;
        width: 0;
        height: 0;
        border-top: 15px solid transparent;
        border-bottom: 15px solid transparent;
        border-right: 15px solid #ee694e;
        left: -15px;
        top: 30%;
    }
    .textbox-container {
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative; 
        margin-top: 20px; 
    }
    .camera-input {
        width: 200px; 
        height: 200px; 
        padding: 0; 
        text-align: center; 
        border: 2px solid #aaa; 
        border-radius: 10px; 
    }
    .actions-container {
        display: flex;
        margin-top: 20px; 
    }
    .flashlight-container,
    .keyboard-container {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 60px;
        height: 60px;
        background-color: #ffffff;
        border-radius: 50%;
        border: 2px solid #ecb054;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }
    .flashlight-container i,
    .keyboard-container i {
        color: #000000;
        font-size: 24px;
    }
    .flashlight-container {
        margin-right: 20px; 
    }
    .keyboard-container {
        margin-left: 20px; 
    }
</style>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Map{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <style>
        .navbar {
          background-color: #b8d171 !important;
        }

        .navbar .nav-link {
          color: #d8ebf7 !important; 
        }
      </style>
      <a class="navbar-brand">
        <img src="logo.png" alt="logo" height="40">
      </a>

      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar"> 
        <div class="navbar-nav">
          
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="map" href="/">Map</a>
          <a class="nav-item nav-link" id="wallet" href="{{ url_for('views.wallet') }}">Wallet</a>
          <a class="nav-item nav-link" id="Co2" href="{{ url_for('views.co2') }}">Co2</a>
          <a class="nav-item nav-link" id="history" href="{{ url_for('views.history') }}">History</a>
          <a class="nav-item nav-link" id="pricing" href="{{ url_for('views.pricing') }}">Pricing</a>
          <a class="nav-item nav-link" id="info" href="{{ url_for('views.info') }}">Info</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signup" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <style>
      body {
        background-color: #d8ebf7; 
        font-family: 'Fredoka One', sans-serif;
        color: #d8ebf7!important;
      }
    </style>
  
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap">

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
        fetch("/delete-note", {
          method: "POST",
          body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
          window.location.href = "/";
        });
      }
    </script>
{% endblock %}
  </body>
</html>

website/templates/day_pass.html
{% extends "base.html" %}
{% block title %}Day Pass{% endblock %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column; /* Added to align items vertically */
        height: 100vh; /* Adjust as needed */
    }
    .box {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        color: grey; /* Adjust text color here */
        text-align: center; 
        margin-top: -10px; 
        border: 2px solid #b8d171;
    }
    .orange-box {
        background-color: #ecb054;
        padding: 10px;
        border-radius: 5px;
        color: white;
        text-align: center;
        margin-bottom: 20px; /* Adjust as needed */
    }
    .pay-button {
        background-color: #ee694e; /* Orange color */
        color: white; /* White text color */
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
        margin-top: 20px;
    }
    .left-align {
        text-align: left; 
    }
    .lock-icon, .bike-icon, .clock-icon, .money-bag-icon, .cart-icon, .wallet-icon {
        color: #ee694e; 
        margin-right: 5px;
    }
    .small-text {
        font-size: 11px; 
        color: grey;
        margin-top: 10px;
    }
    .second-box {
        margin-top: 20px; 
        border: 2px solid #b8d171; 
    }
    .second-box h2 {
        font-size: 14px; 
        margin-bottom: 10px; 
    }
    .second-box p {
        font-size: 10px; 
    }
</style>

<div class="container">
    <div class="box">
        <div class="orange-box">
            <h2>Day Pass</h2>
        </div>
        <div class="left-align">
            <p><i class="fas fa-wallet wallet-icon"></i>10.99</p>
            <p><i class="fas fa-lock lock-icon"></i> Unlimited unlocks</p>
            <p><i class="fas fa-bicycle bike-icon"></i>Access to pedal or electric bikes</p>
            <p><i class="fas fa-clock clock-icon"></i>120 riding minutes</p>
            <p><i class="fas fa-money-bill-wave money-bag-icon"></i>This price is equal to £0.09 per minute.</p>
            <p><i class="fas fa-shopping-cart cart-icon"></i>This pass is a one-time payment and will be valid for 1 day from the time of purchase.</p>
        </div>
        <form id="payment-form" action="/day_pass.html" method="post">
            <button type="submit" class="pay-button">Pay Now</button>
        </form>
        <p class="small-text">This pass will be automatically activated once purchased</p>
    </div>

    <div class="box second-box">
        <h2>Please take into account the following:</h2>
        <p>Once the minutes have been used, the standard rate per minute of £0.17 will be applied.</p>
        <p>You will have access to both pedal bikes and electric bikes with this pass.</p>
    </div>
</div>
{% endblock %}

website/templates/end_journey.html
{% extends "base.html" %}
{% block title %}End Journey{% endblock %}
{% block content %}

<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    /* Styles for the navigation bar */
    .nav-bar {
        /* Your existing styles for the navigation bar */
        /* Example: */
        background-color: #333;
        color: #fff;
        padding: 10px;
    }

    .map-container {
        position: relative;
        display: flex;
        justify-content: center;
        align-items: center;
        height: calc(100vh - 50px); /* Adjusted to account for the height of the navigation bar */
    }

    .google-map {
        width: 70vw;
        max-width: 400px;
        height: 95vh; 
        border: 2px solid #b8d171;
        margin: 30px auto; 
    }

    .google-map iframe {
        width: 100%;
        height: 100%;
        border: 0;
    }

    .rectangular-box {
        position: relative; /* Set position relative for absolute positioning */
        width: 90%;
        max-width: 400px;
        background-color: #ffffff;
        border: 2px solid #b8d171;
        margin: 20px auto; /* Adjusted margin */
        padding: 20px;
        text-align: center;
    }

    .rectangular-box h2 {
        font-size: 16px; 
        margin-bottom: 5px; 
    }

    .rectangular-box p {
        font-size: 14px; 
        margin: 5px 0; 
        display: inline-block; 
    }

    .bike-text {
        font-size: 12px; 
        position: absolute;
        bottom: 5px; 
        left: 5px; 
    }

    .red-box {
        width: 300px;
        height: 100px; 
        background-color: #ecb054;
        margin: 20px auto; 
        display: flex;
        justify-content: center;
        align-items: center;
        color: white;
        text-align: center;
        border-radius: 20px;
    }
</style>

<!-- Red Box -->
<div class="red-box">Ride complete! Thanks for spinning with us – Until the next adventure!</div>

<div class="map-container">
    <div class="google-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1138.505655421684!2d-6.523866243660483!3d55.20056202238702!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48602ee5d32756ad%3A0xf043347e189bd9df!2sBushmills%20Distillery!5e0!3m2!1sen!2suk!4v1708711056958!5m2!1sen!2suk" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>

<div class="rectangular-box">
    <h2>Your Ride Total</h2>
    <p>£2.62</p>
    <p class="bike-text">bike</p>
</div>

{% endblock %}

website/templates/end_journey2.html
{% extends "base.html" %}
{% block title %}End Journey{% endblock %}
{% block content %}

<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    .map-container {
        position: relative;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .google-map {
        width: 70vw;
        max-width: 400px;
        height: 95vh; 
        border: 2px solid #b8d171;
        margin: 30px auto; 
    }

    .google-map iframe {
        width: 100%;
        height: 100%;
        border: 0;
    }

    .rectangular-box {
        position: relative; /* Set position relative for absolute positioning */
        width: 90%;
        max-width: 400px;
        background-color: #ffffff;
        border: 2px solid #b8d171;
        margin: 3px auto; 
        padding: 20px;
        text-align: center;
    }

    .rectangular-box h2 {
        font-size: 16px; 
        margin-bottom: 5px; 
    }

    .rectangular-box p {
        font-size: 14px; 
        margin: 5px 0; 
        display: inline-block; 
    }

    .bike-text {
        font-size: 12px; 
        position: absolute;
        bottom: 5px; 
        left: 5px; 
    }
</style>
<div class="map-container">
    <div class="google-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1138.505655421684!2d-6.523866243660483!3d55.20056202238702!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48602ee5d32756ad%3A0xf043347e189bd9df!2sBushmills%20Distillery!5e0!3m2!1sen!2suk!4v1708711056958!5m2!1sen!2suk" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>

<div class="rectangular-box">
    <h2>Your Ride Total</h2>
    <p>£2.62</p>
    <p class="bike-text">bike</p>
</div>

{% endblock %}

website/templates/history.html
{% extends "base.html" %}
{% block title %}Journey History{% endblock %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<style>
    /* CSS for the white circle */
    .bike-icon {
        position: relative;
        width: 70px; /* Adjust as needed */
        height: 70px; /* Adjust as needed */
        background-color: white;
        border: 3px solid #b8d171; /* Outline color */
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 20px auto; /* Adjust as needed */
    }
</style>

<div class="bike-icon"><i class="fas fa-bicycle fa-2x" style="color: grey;"></i>
</div>

{% endblock %}

website/templates/info.html
{% extends "base.html" %}
{% block title %}Info{% endblock %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Info Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        .textbox {
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
            margin-top: 20px; 
            font-weight: 400; 
            color: white; 
        }
        .textbox h2 {
            margin-top: 0;
            font-weight: 500; 
            text-align: center; 
        }
        .red-textbox {
            background-color: #ee694e; 
        }
        .orange-textbox {
            background-color: #ecb054; 
        }
        .green-textbox {
            background-color: #b8d171; 
        }
        .safety-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between; 
        }
        .safety-list p {
            margin: 10px;
            display: flex;
            align-items: center;
            width: calc(50% - 20px); 
        }
        .safety-list i {
            font-size: 24px; 
            margin-right: 10px; 
            width: 24px; 
            text-align: center; 
        }
    </style>
</head>
<body>
    <div class="textbox red-textbox">
        <h2>How does Greencommute work?</h2>
        <p>
            1. Use the map to find a Greenride. <br>
            2. Scan the QR located on the bike. Once your bike is unlocked and has been paid the journey will begin. <br>
            3. Ride in bike lanes or close to the pavement of the road. <br>
            4. Once finished, select a zone to park near you, end your journey and lock your bike.
        </p>
    </div>

    <div class="textbox orange-textbox">
        <h2>Parking Zone Guide</h2>
        <p>
            <strong>Grey Zone:</strong> This is a no-riding Zone. You cannot ride or park here. <br>
            <strong>Red Zone:</strong> This is a parking Zone. This location is designed for you to park.
        </p>
    </div>

    <div class="textbox green-textbox">
        <h2>Safety</h2>
        <div class="safety-list">
            <p><i class="fas fa-road"></i> Follow the Highway Code</p>
            <p><i class="fas fa-hard-hat"></i> Always wear a helmet</p>
            <p><i class="fas fa-ban"></i> Never drink and ride</p>
            <p><i class="fas fa-parking"></i> Park with thought</p>
        </div>
    </div>
</body>

</html>
{% endblock %}

website/templates/journey.html
{% extends "base.html" %}
{% block title %}Journey{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        .google-map {
            width: 70vw;
            height: 100vh; /* Set height to 100% of viewport height */
            max-width: 400px;
            border: 2px solid #b8d171;
            margin-top: 50px; /* Adjust the margin-top value */
            margin-bottom: 50px; 
            z-index: 1;
            position: relative;
            left: calc(50% + 50px); /* Adjust the value as needed */
            transform: translateX(-50%);
        }
        .google-map iframe {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border: 0;
        }
        .scan-button, .textbox {
            position: absolute;
            bottom: 20px; 
            left: 50%;
            transform: translateX(-50%);
            z-index: 1000; 
            text-align: center;
        }
        .icon-container {
            background-color: #ee694e; 
            padding: 5px 60px;
            border-radius: 10px; 
            display: inline-block; 
        }
        .textbox {
            background-color: #ecb054;
            padding: 5px 10px;
            border-radius: 10px;
            color: white;
            font-size: 12px; 
            bottom: 70px; 
        }
    </style>
</head>

<body>
    <div class="google-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1138.505655421684!2d-6.523866243660483!3d55.20056202238702!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48602ee5d32756ad%3A0xf043347e189bd9df!2sBushmills%20Distillery!5e0!3m2!1sen!2suk!4v1708711056958!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        <div class="scan-button">
            <a href="begin_journey.html">
                <button style="background-color: #ee694e; color: white; padding: 10px 20px; border: none; border-radius: 15px;">Begin Journey</button>
            </a>
        </div>
        <div class="textbox">
            JH245
        </div>
    </div>
</body>
{% endblock %}